spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/performance?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: geniusadmin!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always